import PDFDocument from "pdfkit";

export const generateAgreementPDF = (data, res) => {

  const doc = new PDFDocument();

  res.setHeader(
    "Content-Type",
    "application/pdf"
  );

  res.setHeader(
    "Content-Disposition",
    `attachment; filename=SocialEdger-INFTO-${data.wallet}.pdf`
  );

  doc.pipe(res);

  doc.fontSize(22)
    .text("SocialEdger INFTO Participation Agreement", {
      align: "center",
    });

  doc.moveDown();

  doc.fontSize(12).text(`
This document confirms that the wallet holder listed below
has digitally accepted the SocialEdger INFTO Participation Agreement.

The acceptance was recorded through a cryptographic wallet
signature which uniquely proves ownership of the wallet address.

This document serves as proof of participation within the
SocialEdger ecosystem.

------------------------------------------------------------

Wallet Address
${data.wallet}

------------------------------------------------------------

Agreement Timestamp
${data.createdAt}

------------------------------------------------------------

Cryptographic Signature
${data.signature}

------------------------------------------------------------

Agreement Hash
${data.signature.slice(0, 20)}...

------------------------------------------------------------

By signing the INFTO agreement the participant acknowledges
that they understand the SocialEdger ecosystem participation
rules and that blockchain transactions are irreversible.

Membership NFTs provide ecosystem access, governance
participation, and token mining benefits.

Participation in decentralized ecosystems carries
financial and technological risks which the participant
acknowledges and accepts.

------------------------------------------------------------
`);

  doc.moveDown();

  doc.fontSize(14).text("SocialEdger Management Signature");

  doc.moveDown();

  doc.image(
    "public/signature.png",
    {
      width: 200,
      align: "left"
    }
  );

  doc.moveDown();

  doc.fontSize(10).text(
    "This document was automatically generated by the SocialEdger INFTO verification system."
  );

  doc.end();
};